### ISSUE TITLE
require_once error

### ISSUE THREAD

**Issue by interlab** [Spuds/Elk-PDF#1]
ELK2PDF     1.0.2

file: /.../sources/subs/Elk_PDF.class.php

error:

```
require_once(/.../sources/subs/Aeva-Subs.php): failed to open stream: No such file or directory
```

**Comment by Spuds** [comment]
Whoopsie ... how did that get in there :innocent: 

Really Its an example gallery block I added but forgot to not call it from the main code when I did the last update.  Will fix soon!
